name       : evopop-icon-theme
version    : 0.11
release    : 10
source     :
    - git|https://github.com/solus-cold-storage/evopop-icon-theme : cafb3a200a1de7d6afc9499c89732bcfb9b93230
license    : CC-BY-4.0
summary    : EvoPop Icon Theme
component  : desktop.theme
description: |
    A simple icon theme with some google material design inspiration.
setup      : |
    %apply_patches
    %autogen
build      : |
    %make
install    : |
    %make_install

    # Fix file permissions
    chmod -R 00644 $installdir/usr/share/icons/EvoPop/*
