name       : evopop-icon-theme
version    : 0.11
release    : 9
source     :
    - https://github.com/solus-cold-storage/evopop-icon-theme/archive/0.11.tar.gz : 28131eddd56a65c152ae9a05950c0c4a972860c641be3e592f2d10622b75f9f2
license    : CC-BY-4.0
summary    : EvoPop Icon Theme
component  : desktop.theme
description: |
    A simple icon theme with some google material design inspiration.
setup      : |
    %autogen
build      : |
    %make
install    : |
    %make_install
